version: '3' 
services:
  app:
    image: wordpress
    container_name: wordpress
    hostname: wordpress
    ports: 
      - 80:80
    restart: always
    environment: 
      WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
#    depends_on: 
#      - db
